<?php

/*
Advanced Custom Field Settings

Contains all of the advanced custom field setting for Slickity.

Last Updated: December 8, 2017
*/

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
  'key' => 'group_5a2598b9d9e37',
  'title' => 'Slickity Options',
  'fields' => array(
    array(
      'key' => 'field_5a2598fca8f9d',
      'label' => 'Slides',
      'name' => '',
      'type' => 'tab',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'placement' => 'top',
      'endpoint' => 0,
    ),
    array(
      'key' => 'field_5a2599640053d',
      'label' => 'Slides',
      'name' => 'slickity_slides',
      'type' => 'repeater',
      'instructions' => 'Click \'Add Slide\' to create a new slide for the slideshow.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'collapsed' => '',
      'min' => 0,
      'max' => 0,
      'layout' => 'block',
      'button_label' => 'Add Slide',
      'sub_fields' => array(
        array(
          'key' => 'field_5a2599f584352',
          'label' => 'Slide',
          'name' => '',
          'type' => 'tab',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'placement' => 'top',
          'endpoint' => 0,
        ),
        array(
          'key' => 'field_5a2973e351dc5',
          'label' => 'Use Template',
          'name' => 'template',
          'type' => 'true_false',
          'instructions' => 'Enable to use a predefined slide template.',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '50',
            'class' => '',
            'id' => '',
          ),
          'message' => '',
          'default_value' => 1,
          'ui' => 1,
          'ui_on_text' => 'True',
          'ui_off_text' => 'False',
        ),
        array(
          'key' => 'field_5a27035736406',
          'label' => 'Custom Thumbnail',
          'name' => 'thumbnail',
          'type' => 'true_false',
          'instructions' => 'Override the default thumbnail slide content when  \'Thumbnail Slideshow\' is enabled.',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '50',
            'class' => '',
            'id' => '',
          ),
          'message' => '',
          'default_value' => 0,
          'ui' => 1,
          'ui_on_text' => 'True',
          'ui_off_text' => 'False',
        ),
        array(
          'key' => 'field_5a2988670daae',
          'label' => 'Available Templates',
          'name' => 'templates',
          'type' => 'group',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => array(
            array(
              array(
                'field' => 'field_5a2973e351dc5',
                'operator' => '==',
                'value' => '1',
              ),
            ),
          ),
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'layout' => 'block',
          'sub_fields' => array(
            array(
              'key' => 'field_5a29878365ad6',
              'label' => 'Template',
              'name' => 'template',
              'type' => 'select',
              'instructions' => 'Select the template for this slide below.',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'choices' => array(
                'default' => 'Default Template (image & caption)',
              ),
              'default_value' => array(
                0 => 'default',
              ),
              'allow_null' => 0,
              'multiple' => 0,
              'ui' => 1,
              'ajax' => 0,
              'return_format' => 'value',
              'placeholder' => '',
            ),
            array(
              'key' => 'field_5a29890a140f0',
              'label' => 'Default Template (image & caption)',
              'name' => 'default',
              'type' => 'group',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => array(
                array(
                  array(
                    'field' => 'field_5a29878365ad6',
                    'operator' => '==',
                    'value' => 'default',
                  ),
                ),
              ),
              'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'layout' => 'block',
              'sub_fields' => array(
                array(
                  'key' => 'field_5a29894eb185e',
                  'label' => 'Image',
                  'name' => 'image',
                  'type' => 'image',
                  'instructions' => 'Click \'Add Image\' to upload the slide image.',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                  ),
                  'return_format' => 'array',
                  'preview_size' => 'thumbnail',
                  'library' => 'all',
                  'min_width' => '',
                  'min_height' => '',
                  'min_size' => '',
                  'max_width' => '',
                  'max_height' => '',
                  'max_size' => '',
                  'mime_types' => '',
                ),
                array(
                  'key' => 'field_5a29911a717ab',
                  'label' => 'Image Size',
                  'name' => 'image_size',
                  'type' => 'radio',
                  'instructions' => 'Optional image size. Enter a custom one if needed.',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                  ),
                  'choices' => array(
                    'thumbnail' => 'Thumbnail',
                    'medium' => 'Medium',
                    'medium_large' => 'Medium - Large',
                    'large' => 'Large',
                    'full' => 'Full',
                  ),
                  'allow_null' => 0,
                  'other_choice' => 1,
                  'save_other_choice' => 1,
                  'default_value' => 'full',
                  'layout' => 'vertical',
                  'return_format' => 'value',
                ),
                array(
                  'key' => 'field_5a298968b185f',
                  'label' => 'Caption',
                  'name' => 'caption',
                  'type' => 'wysiwyg',
                  'instructions' => 'Optional image caption text.',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'default_value' => '',
                  'tabs' => 'all',
                  'toolbar' => 'basic',
                  'media_upload' => 0,
                  'delay' => 0,
                ),
                array(
                  'key' => 'field_5a299de9e472c',
                  'label' => 'Text Color',
                  'name' => 'text_color',
                  'type' => 'color_picker',
                  'instructions' => 'Caption text color.',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '33.333333333333333',
                    'class' => '',
                    'id' => '',
                  ),
                  'default_value' => '#ffffff',
                ),
                array(
                  'key' => 'field_5a299ccca15b7',
                  'label' => 'Background Color',
                  'name' => 'bg_color',
                  'type' => 'color_picker',
                  'instructions' => 'Background color for the caption text.',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '33.333333333333333',
                    'class' => '',
                    'id' => '',
                  ),
                  'default_value' => '#000000',
                ),
                array(
                  'key' => 'field_5a299d49a15b8',
                  'label' => 'Background Opacity',
                  'name' => 'bg_opacity',
                  'type' => 'number',
                  'instructions' => 'Opacity for the background color.',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '33.333333333333333',
                    'class' => '',
                    'id' => '',
                  ),
                  'default_value' => 85,
                  'placeholder' => '',
                  'prepend' => '',
                  'append' => '%',
                  'min' => 0,
                  'max' => 100,
                  'step' => 1,
                ),
              ),
            ),
          ),
        ),
        array(
          'key' => 'field_5a259a429f20b',
          'label' => 'Content',
          'name' => 'slide_content',
          'type' => 'wysiwyg',
          'instructions' => 'Create the slide content below.',
          'required' => 0,
          'conditional_logic' => array(
            array(
              array(
                'field' => 'field_5a2973e351dc5',
                'operator' => '!=',
                'value' => '1',
              ),
            ),
          ),
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'tabs' => 'all',
          'toolbar' => 'full',
          'media_upload' => 1,
          'delay' => 0,
        ),
        array(
          'key' => 'field_5a2813e745a0c',
          'label' => 'CSS Class',
          'name' => 'css',
          'type' => 'text',
          'instructions' => 'You can easily style each slide by adding a CSS class below. Separate multiple classes with a space.',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'maxlength' => '',
        ),
        array(
          'key' => 'field_5a27154183748',
          'label' => 'Thumbnail',
          'name' => '',
          'type' => 'tab',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => array(
            array(
              array(
                'field' => 'field_5a27035736406',
                'operator' => '==',
                'value' => '1',
              ),
            ),
          ),
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'placement' => 'top',
          'endpoint' => 0,
        ),
        array(
          'key' => 'field_5a280f78af4bf',
          'label' => 'Thumbnail Content',
          'name' => 'thumbnail_content',
          'type' => 'wysiwyg',
          'instructions' => 'Create the thumbnail content below.',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'tabs' => 'all',
          'toolbar' => 'full',
          'media_upload' => 1,
          'delay' => 0,
        ),
        array(
          'key' => 'field_5a2814caf07a3',
          'label' => 'CSS Class',
          'name' => 'thumbnail_css',
          'type' => 'text',
          'instructions' => 'You can easily style each thumbnail by adding a CSS class below. Separate multiple classes with a space.',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'maxlength' => '',
        ),
        array(
          'key' => 'field_5a2599db84351',
          'label' => 'Schedule',
          'name' => '',
          'type' => 'tab',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'placement' => 'top',
          'endpoint' => 0,
        ),
        array(
          'key' => 'field_5a298c0511b46',
          'label' => 'Coming Soon',
          'name' => '',
          'type' => 'message',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'message' => 'Slide schedules coming soon!',
          'new_lines' => 'wpautop',
          'esc_html' => 0,
        ),
      ),
    ),
    array(
      'key' => 'field_5a259947a8f9e',
      'label' => 'Slideshow Options',
      'name' => '',
      'type' => 'tab',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'placement' => 'top',
      'endpoint' => 0,
    ),
    array(
      'key' => 'field_5a26ac33fd41e',
      'label' => 'Enable Thumbnails',
      'name' => 'slickity_thumbnail',
      'type' => 'true_false',
      'instructions' => 'Displays a thumbnail slideshow directly below the main slideshow.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '50',
        'class' => '',
        'id' => '',
      ),
      'message' => '',
      'default_value' => 0,
      'ui' => 1,
      'ui_on_text' => 'True',
      'ui_off_text' => 'False',
    ),
    array(
      'key' => 'field_5a2a995f2770d',
      'label' => 'Enable Lightbox',
      'name' => 'slickity_lightbox',
      'type' => 'true_false',
      'instructions' => 'Displays a lightbox gallery when the user clicks on a slide.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '50',
        'class' => '',
        'id' => '',
      ),
      'message' => '',
      'default_value' => 0,
      'ui' => 1,
      'ui_on_text' => 'True',
      'ui_off_text' => 'False',
    ),
    array(
      'key' => 'field_5a26ae7d3606d',
      'label' => 'Main Slideshow Settings',
      'name' => 'slickity_main_settings',
      'type' => 'group',
      'instructions' => 'For more information on the available settings, see <a href="http://kenwheeler.github.io/slick/#settings" target="_blank">http://kenwheeler.github.io/slick/#settings</a>.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'layout' => 'block',
      'sub_fields' => array(
        array(
          'key' => 'field_5a29aac9dddfa',
          'label' => 'Template',
          'name' => 'template',
          'type' => 'select',
          'instructions' => 'Select the template for this slide container below, includes styling for the arrows and dots.',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '25',
            'class' => '',
            'id' => '',
          ),
          'choices' => array(
            0 => 'No Template',
            'default' => 'Default Template',
          ),
          'default_value' => array(
            0 => 0,
          ),
          'allow_null' => 0,
          'multiple' => 0,
          'ui' => 1,
          'ajax' => 0,
          'return_format' => 'value',
          'placeholder' => '',
        ),
        array(
          'key' => 'field_5a2815486913b',
          'label' => 'CSS Class',
          'name' => 'css',
          'type' => 'text',
          'instructions' => 'You can easily style the slideshow by adding a CSS class below. Separate multiple classes with a space.',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '25',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'maxlength' => '',
        ),
        array(
          'key' => 'field_5a26b48e0e101',
          'label' => 'Slides to Show',
          'name' => 'slidesToShow',
          'type' => 'number',
          'instructions' => 'Number of slides to show.',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '25',
            'class' => '',
            'id' => '',
          ),
          'default_value' => 1,
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'min' => 1,
          'max' => '',
          'step' => 1,
        ),
        array(
          'key' => 'field_5a26b4c50e102',
          'label' => 'Slides to Scroll',
          'name' => 'slidesToScroll',
          'type' => 'number',
          'instructions' => 'Number of slides to scroll.',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '25',
            'class' => '',
            'id' => '',
          ),
          'default_value' => 1,
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'min' => 1,
          'max' => '',
          'step' => 1,
        ),
        array(
          'key' => 'field_5a26b316da877',
          'label' => 'Infinite',
          'name' => 'infinite',
          'type' => 'true_false',
          'instructions' => 'Enable infinite loop sliding.',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '25',
            'class' => '',
            'id' => '',
          ),
          'message' => '',
          'default_value' => 1,
          'ui' => 1,
          'ui_on_text' => 'True',
          'ui_off_text' => 'False',
        ),
        array(
          'key' => 'field_5a26af3eed289',
          'label' => 'Adaptive Height',
          'name' => 'adaptiveHeight',
          'type' => 'true_false',
          'instructions' => 'Enables adaptive height for single slide horizontal carousels.',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '25',
            'class' => '',
            'id' => '',
          ),
          'message' => '',
          'default_value' => 0,
          'ui' => 1,
          'ui_on_text' => 'True',
          'ui_off_text' => 'False',
        ),
        array(
          'key' => 'field_5a26b120efdb4',
          'label' => 'Autoplay',
          'name' => 'autoplay',
          'type' => 'true_false',
          'instructions' => 'Enables autoplay of the slideshow.',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '25',
            'class' => '',
            'id' => '',
          ),
          'message' => '',
          'default_value' => 0,
          'ui' => 1,
          'ui_on_text' => 'True',
          'ui_off_text' => 'False',
        ),
        array(
          'key' => 'field_5a26b1e6da873',
          'label' => 'Arrows',
          'name' => 'arrows',
          'type' => 'true_false',
          'instructions' => 'Enable prev/next arrows.',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '25',
            'class' => '',
            'id' => '',
          ),
          'message' => '',
          'default_value' => 1,
          'ui' => 1,
          'ui_on_text' => 'True',
          'ui_off_text' => 'False',
        ),
        array(
          'key' => 'field_5a26b238da874',
          'label' => 'Previous Arrow',
          'name' => 'prevArrow',
          'type' => 'text',
          'instructions' => 'Allows you to customize the HTML for the "Previous" arrow. Accepts HTML.',
          'required' => 0,
          'conditional_logic' => array(
            array(
              array(
                'field' => 'field_5a26b1e6da873',
                'operator' => '==',
                'value' => '1',
              ),
              array(
                'field' => 'field_5a29aac9dddfa',
                'operator' => '==',
                'value' => '0',
              ),
            ),
          ),
          'wrapper' => array(
            'width' => '25',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '<button type="button" class="slick-prev">Previous</button>',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'maxlength' => '',
        ),
        array(
          'key' => 'field_5a26b2a1da875',
          'label' => 'Next Arrow',
          'name' => 'nextArrow',
          'type' => 'text',
          'instructions' => 'Allows you to customize the HTML for the "Next" arrow. Accepts HTML.',
          'required' => 0,
          'conditional_logic' => array(
            array(
              array(
                'field' => 'field_5a26b1e6da873',
                'operator' => '==',
                'value' => '1',
              ),
              array(
                'field' => 'field_5a29aac9dddfa',
                'operator' => '==',
                'value' => '0',
              ),
            ),
          ),
          'wrapper' => array(
            'width' => '25',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '<button type="button" class="slick-next">Next</button>',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'maxlength' => '',
        ),
        array(
          'key' => 'field_5a26b2d8da876',
          'label' => 'Dots',
          'name' => 'dots',
          'type' => 'true_false',
          'instructions' => 'Enable dot indicators.',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '25',
            'class' => '',
            'id' => '',
          ),
          'message' => '',
          'default_value' => 0,
          'ui' => 1,
          'ui_on_text' => 'True',
          'ui_off_text' => 'False',
        ),
        array(
          'key' => 'field_5a26cf4ee4cc8',
          'label' => 'Responsive Settings',
          'name' => 'responsive',
          'type' => 'true_false',
          'instructions' => 'Define settings for individual breakpoints.',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '25',
            'class' => '',
            'id' => '',
          ),
          'message' => '',
          'default_value' => 0,
          'ui' => 1,
          'ui_on_text' => 'True',
          'ui_off_text' => 'False',
        ),
        array(
          'key' => 'field_5a26d085e62c2',
          'label' => 'Mobile First',
          'name' => 'mobileFirst',
          'type' => 'true_false',
          'instructions' => 'Enable to apply main settings to mobile first.',
          'required' => 0,
          'conditional_logic' => array(
            array(
              array(
                'field' => 'field_5a26cf4ee4cc8',
                'operator' => '==',
                'value' => '1',
              ),
            ),
          ),
          'wrapper' => array(
            'width' => '25',
            'class' => '',
            'id' => '',
          ),
          'message' => '',
          'default_value' => 0,
          'ui' => 1,
          'ui_on_text' => 'True',
          'ui_off_text' => 'False',
        ),
        array(
          'key' => 'field_5a26bddf09f8a',
          'label' => 'Responsive Options',
          'name' => 'responsive_options',
          'type' => 'repeater',
          'instructions' => 'Click \'Add Breakpoint\' to define settings for individual breakpoints, then click \'Add Setting\' to add additional settings. For information on the available settings, see <a href="http://kenwheeler.github.io/slick/#settings" target="_blank">http://kenwheeler.github.io/slick/#settings</a>.',
          'required' => 1,
          'conditional_logic' => array(
            array(
              array(
                'field' => 'field_5a26cf4ee4cc8',
                'operator' => '==',
                'value' => '1',
              ),
            ),
          ),
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'collapsed' => '',
          'min' => 0,
          'max' => 0,
          'layout' => 'block',
          'button_label' => 'Add Breakpoint',
          'sub_fields' => array(
            array(
              'key' => 'field_5a26be89b058c',
              'label' => 'Breakpoint',
              'name' => 'breakpoint',
              'type' => 'number',
              'instructions' => '',
              'required' => 1,
              'conditional_logic' => 0,
              'wrapper' => array(
                'width' => '15',
                'class' => '',
                'id' => '',
              ),
              'default_value' => 728,
              'placeholder' => '',
              'prepend' => '',
              'append' => 'px',
              'min' => 1,
              'max' => '',
              'step' => 1,
            ),
            array(
              'key' => 'field_5a26bed7b058d',
              'label' => 'Settings',
              'name' => 'settings',
              'type' => 'repeater',
              'instructions' => '',
              'required' => 1,
              'conditional_logic' => 0,
              'wrapper' => array(
                'width' => '85',
                'class' => '',
                'id' => '',
              ),
              'collapsed' => '',
              'min' => 0,
              'max' => 0,
              'layout' => 'table',
              'button_label' => 'Add Setting',
              'sub_fields' => array(
                array(
                  'key' => 'field_5a26c283022b1',
                  'label' => 'Setting',
                  'name' => 'setting',
                  'type' => 'select',
                  'instructions' => '',
                  'required' => 1,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                  ),
                  'choices' => array(
                    'accessibility' => 'accessibility',
                    'adaptiveHeight' => 'adaptiveHeight',
                    'autoplay' => 'autoplay',
                    'autoplaySpeed' => 'autoplaySpeed',
                    'arrows' => 'arrows',
                    'asNavFor' => 'asNavFor',
                    'appendArrows' => 'appendArrows',
                    'appendDots' => 'appendDots',
                    'prevArrow' => 'prevArrow',
                    'nextArrow' => 'nextArrow',
                    'centerMode' => 'centerMode',
                    'centerPadding' => 'centerPadding',
                    'cssEase' => 'cssEase',
                    'customPaging' => 'customPaging',
                    'dots' => 'dots',
                    'dotsClass' => 'dotsClass',
                    'draggable' => 'draggable',
                    'fade' => 'fade',
                    'focusOnSelect' => 'focusOnSelect',
                    'easing' => 'easing',
                    'edgeFriction' => 'edgeFriction',
                    'infinite' => 'infinite',
                    'initialSlide' => 'initialSlide',
                    'lazyLoad' => 'lazyLoad',
                    'mobileFirst' => 'mobileFirst',
                    'pauseOnFocus' => 'pauseOnFocus',
                    'pauseOnHover' => 'pauseOnHover',
                    'pauseOnDotsHover' => 'pauseOnDotsHover',
                    'respondTo' => 'respondTo',
                    'rows' => 'rows',
                    'slide' => 'slide',
                    'slidesPerRow' => 'slidesPerRow',
                    'slidesToShow' => 'slidesToShow',
                    'slidesToScroll' => 'slidesToScroll',
                    'speed' => 'speed',
                    'swipe' => 'swipe',
                    'swipeToSlide' => 'swipeToSlide',
                    'touchMove' => 'touchMove',
                    'touchThreshold' => 'touchThreshold',
                    'useCSS' => 'useCSS',
                    'useTransform' => 'useTransform',
                    'variableWidth' => 'variableWidth',
                    'vertical' => 'vertical',
                    'verticalSwiping' => 'verticalSwiping',
                    'rtl' => 'rtl',
                    'waitForAnimate' => 'waitForAnimate',
                    'zIndex' => 'zIndex',
                  ),
                  'default_value' => array(
                  ),
                  'allow_null' => 0,
                  'multiple' => 0,
                  'ui' => 1,
                  'ajax' => 0,
                  'return_format' => 'value',
                  'placeholder' => '',
                ),
                array(
                  'key' => 'field_5a26c29d022b2',
                  'label' => 'Value',
                  'name' => 'value',
                  'type' => 'textarea',
                  'instructions' => '',
                  'required' => 1,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                  'maxlength' => '',
                  'rows' => '',
                  'new_lines' => '',
                ),
              ),
            ),
          ),
        ),
        array(
          'key' => 'field_5a26aea13606e',
          'label' => 'Additional Settings',
          'name' => 'additional_settings',
          'type' => 'repeater',
          'instructions' => 'Click \'Add Setting\' to add additional settings. For information on the available settings, see <a href="http://kenwheeler.github.io/slick/#settings" target="_blank">http://kenwheeler.github.io/slick/#settings</a>.',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'collapsed' => '',
          'min' => 0,
          'max' => 0,
          'layout' => 'table',
          'button_label' => 'Add Setting',
          'sub_fields' => array(
            array(
              'key' => 'field_5a26c5a2feaa7',
              'label' => 'Setting',
              'name' => 'setting',
              'type' => 'select',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
              ),
              'choices' => array(
                'accessibility' => 'accessibility',
                'autoplaySpeed' => 'autoplaySpeed',
                'asNavFor' => 'asNavFor',
                'appendArrows' => 'appendArrows',
                'appendDots' => 'appendDots',
                'centerMode' => 'centerMode',
                'centerPadding' => 'centerPadding',
                'cssEase' => 'cssEase',
                'customPaging' => 'customPaging',
                'dotsClass' => 'dotsClass',
                'draggable' => 'draggable',
                'fade' => 'fade',
                'focusOnSelect' => 'focusOnSelect',
                'easing' => 'easing',
                'edgeFriction' => 'edgeFriction',
                'initialSlide' => 'initialSlide',
                'lazyLoad' => 'lazyLoad',
                'pauseOnFocus' => 'pauseOnFocus',
                'pauseOnHover' => 'pauseOnHover',
                'pauseOnDotsHover' => 'pauseOnDotsHover',
                'respondTo' => 'respondTo',
                'rows' => 'rows',
                'slide' => 'slide',
                'slidesPerRow' => 'slidesPerRow',
                'speed' => 'speed',
                'swipe' => 'swipe',
                'swipeToSlide' => 'swipeToSlide',
                'touchMove' => 'touchMove',
                'touchThreshold' => 'touchThreshold',
                'useCSS' => 'useCSS',
                'useTransform' => 'useTransform',
                'variableWidth' => 'variableWidth',
                'vertical' => 'vertical',
                'verticalSwiping' => 'verticalSwiping',
                'rtl' => 'rtl',
                'waitForAnimate' => 'waitForAnimate',
                'zIndex' => 'zIndex',
              ),
              'default_value' => array(
              ),
              'allow_null' => 0,
              'multiple' => 0,
              'ui' => 1,
              'ajax' => 0,
              'return_format' => 'value',
              'placeholder' => '',
            ),
            array(
              'key' => 'field_5a26c5c5feaa8',
              'label' => 'Value',
              'name' => 'value',
              'type' => 'textarea',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => '',
              'maxlength' => '',
              'rows' => '',
              'new_lines' => '',
            ),
          ),
        ),
      ),
    ),
    array(
      'key' => 'field_5a26bdac09f88',
      'label' => 'Thumbnail Options',
      'name' => '',
      'type' => 'tab',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => array(
        array(
          array(
            'field' => 'field_5a26ac33fd41e',
            'operator' => '==',
            'value' => '1',
          ),
        ),
      ),
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'placement' => 'top',
      'endpoint' => 0,
    ),
    array(
      'key' => 'field_5a26ca8945aa7',
      'label' => 'Thumbnail Slideshow Settings',
      'name' => 'slickity_thumbnail_settings',
      'type' => 'group',
      'instructions' => 'For more information on the available settings, see <a href="http://kenwheeler.github.io/slick/#settings" target="_blank">http://kenwheeler.github.io/slick/#settings</a>.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'layout' => 'block',
      'sub_fields' => array(
        array(
          'key' => 'field_5a29aed567c68',
          'label' => 'Template',
          'name' => 'template',
          'type' => 'select',
          'instructions' => 'Select the template for the thumbnail slide container below, includes styling for the arrows and dots.',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '25',
            'class' => '',
            'id' => '',
          ),
          'choices' => array(
            0 => 'No Template',
            'default' => 'Default Template',
          ),
          'default_value' => array(
            0 => 0,
          ),
          'allow_null' => 0,
          'multiple' => 0,
          'ui' => 1,
          'ajax' => 0,
          'return_format' => 'value',
          'placeholder' => '',
        ),
        array(
          'key' => 'field_5a2815e6601be',
          'label' => 'CSS Class',
          'name' => 'css',
          'type' => 'text',
          'instructions' => 'You can easily style the thumbnail slideshow by adding a CSS class below. Separate multiple classes with a space.',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '25',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'maxlength' => '',
        ),
        array(
          'key' => 'field_5a26cab545aa8',
          'label' => 'Slides to Show',
          'name' => 'slidesToShow',
          'type' => 'number',
          'instructions' => 'Number of slides to show.',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '25',
            'class' => '',
            'id' => '',
          ),
          'default_value' => 1,
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'min' => 1,
          'max' => '',
          'step' => 1,
        ),
        array(
          'key' => 'field_5a26caf345aaa',
          'label' => 'Adaptive Height',
          'name' => 'adaptiveHeight',
          'type' => 'true_false',
          'instructions' => 'Enables adaptive height for single slide horizontal carousels.',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '25',
            'class' => '',
            'id' => '',
          ),
          'message' => '',
          'default_value' => 0,
          'ui' => 1,
          'ui_on_text' => 'True',
          'ui_off_text' => 'False',
        ),
        array(
          'key' => 'field_5a26cb3745aab',
          'label' => 'Arrows',
          'name' => 'arrows',
          'type' => 'true_false',
          'instructions' => 'Enable prev/next arrows.',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '25',
            'class' => '',
            'id' => '',
          ),
          'message' => '',
          'default_value' => 1,
          'ui' => 1,
          'ui_on_text' => 'True',
          'ui_off_text' => 'False',
        ),
        array(
          'key' => 'field_5a26cb9e45aac',
          'label' => 'Previous Arrow',
          'name' => 'prevArrow',
          'type' => 'text',
          'instructions' => 'Allows you to customize the HTML for the "Previous" arrow. Accepts HTML.',
          'required' => 0,
          'conditional_logic' => array(
            array(
              array(
                'field' => 'field_5a26cb3745aab',
                'operator' => '==',
                'value' => '1',
              ),
              array(
                'field' => 'field_5a29aed567c68',
                'operator' => '==',
                'value' => '0',
              ),
            ),
          ),
          'wrapper' => array(
            'width' => '25',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '<button type="button" class="slick-prev">Previous</button>',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'maxlength' => '',
        ),
        array(
          'key' => 'field_5a26cbb545aad',
          'label' => 'Next Arrow',
          'name' => 'nextArrow',
          'type' => 'text',
          'instructions' => 'Allows you to customize the HTML for the "Next" arrow. Accepts HTML.',
          'required' => 0,
          'conditional_logic' => array(
            array(
              array(
                'field' => 'field_5a26cb3745aab',
                'operator' => '==',
                'value' => '1',
              ),
              array(
                'field' => 'field_5a29aed567c68',
                'operator' => '==',
                'value' => '0',
              ),
            ),
          ),
          'wrapper' => array(
            'width' => '25',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '<button type="button" class="slick-next">Next</button>',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'maxlength' => '',
        ),
        array(
          'key' => 'field_5a26cbd145aae',
          'label' => 'Dots',
          'name' => 'dots',
          'type' => 'true_false',
          'instructions' => 'Enable dot indicators.',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '25',
            'class' => '',
            'id' => '',
          ),
          'message' => '',
          'default_value' => 0,
          'ui' => 1,
          'ui_on_text' => 'True',
          'ui_off_text' => 'False',
        ),
        array(
          'key' => 'field_5a26cea27fc2b',
          'label' => 'Responsive Settings',
          'name' => 'responsive',
          'type' => 'true_false',
          'instructions' => 'Define settings for individual breakpoints.',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '25',
            'class' => '',
            'id' => '',
          ),
          'message' => '',
          'default_value' => 0,
          'ui' => 1,
          'ui_on_text' => 'True',
          'ui_off_text' => 'False',
        ),
        array(
          'key' => 'field_5a26d7b1cee67',
          'label' => 'Mobile First',
          'name' => 'mobileFirst',
          'type' => 'true_false',
          'instructions' => 'Applies the main settings to mobile first.',
          'required' => 0,
          'conditional_logic' => array(
            array(
              array(
                'field' => 'field_5a26cea27fc2b',
                'operator' => '==',
                'value' => '1',
              ),
            ),
          ),
          'wrapper' => array(
            'width' => '25',
            'class' => '',
            'id' => '',
          ),
          'message' => '',
          'default_value' => 0,
          'ui' => 1,
          'ui_on_text' => 'True',
          'ui_off_text' => 'False',
        ),
        array(
          'key' => 'field_5a26d695bc6bb',
          'label' => 'Responsive Options',
          'name' => 'responsive_options',
          'type' => 'repeater',
          'instructions' => 'Click \'Add Breakpoint\' to define settings for individual breakpoints, then click \'Add Setting\' to add additional settings. For information on the available settings, see <a href="http://kenwheeler.github.io/slick/#settings" target="_blank">http://kenwheeler.github.io/slick/#settings</a>.',
          'required' => 1,
          'conditional_logic' => array(
            array(
              array(
                'field' => 'field_5a26cea27fc2b',
                'operator' => '==',
                'value' => '1',
              ),
            ),
          ),
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'collapsed' => '',
          'min' => 0,
          'max' => 0,
          'layout' => 'block',
          'button_label' => 'Add Breakpoint',
          'sub_fields' => array(
            array(
              'key' => 'field_5a26d6bebc6bc',
              'label' => 'Breakpoint',
              'name' => 'breakpoint',
              'type' => 'number',
              'instructions' => '',
              'required' => 1,
              'conditional_logic' => 0,
              'wrapper' => array(
                'width' => '15',
                'class' => '',
                'id' => '',
              ),
              'default_value' => 728,
              'placeholder' => '',
              'prepend' => '',
              'append' => 'px',
              'min' => 1,
              'max' => '',
              'step' => 1,
            ),
            array(
              'key' => 'field_5a26d6f0bc6bd',
              'label' => 'Settings',
              'name' => 'settings',
              'type' => 'repeater',
              'instructions' => '',
              'required' => 1,
              'conditional_logic' => 0,
              'wrapper' => array(
                'width' => '85',
                'class' => '',
                'id' => '',
              ),
              'collapsed' => '',
              'min' => 0,
              'max' => 0,
              'layout' => 'table',
              'button_label' => 'Add Setting',
              'sub_fields' => array(
                array(
                  'key' => 'field_5a26d70abc6be',
                  'label' => 'Setting',
                  'name' => 'setting',
                  'type' => 'select',
                  'instructions' => '',
                  'required' => 1,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                  ),
                  'choices' => array(
                    'accessibility' => 'accessibility',
                    'adaptiveHeight' => 'adaptiveHeight',
                    'autoplay' => 'autoplay',
                    'autoplaySpeed' => 'autoplaySpeed',
                    'arrows' => 'arrows',
                    'asNavFor' => 'asNavFor',
                    'appendArrows' => 'appendArrows',
                    'appendDots' => 'appendDots',
                    'prevArrow' => 'prevArrow',
                    'nextArrow' => 'nextArrow',
                    'centerMode' => 'centerMode',
                    'centerPadding' => 'centerPadding',
                    'cssEase' => 'cssEase',
                    'customPaging' => 'customPaging',
                    'dots' => 'dots',
                    'dotsClass' => 'dotsClass',
                    'draggable' => 'draggable',
                    'fade' => 'fade',
                    'focusOnSelect' => 'focusOnSelect',
                    'easing' => 'easing',
                    'edgeFriction' => 'edgeFriction',
                    'infinite' => 'infinite',
                    'initialSlide' => 'initialSlide',
                    'lazyLoad' => 'lazyLoad',
                    'mobileFirst' => 'mobileFirst',
                    'pauseOnFocus' => 'pauseOnFocus',
                    'pauseOnHover' => 'pauseOnHover',
                    'pauseOnDotsHover' => 'pauseOnDotsHover',
                    'respondTo' => 'respondTo',
                    'rows' => 'rows',
                    'slide' => 'slide',
                    'slidesPerRow' => 'slidesPerRow',
                    'slidesToShow' => 'slidesToShow',
                    'slidesToScroll' => 'slidesToScroll',
                    'speed' => 'speed',
                    'swipe' => 'swipe',
                    'swipeToSlide' => 'swipeToSlide',
                    'touchMove' => 'touchMove',
                    'touchThreshold' => 'touchThreshold',
                    'useCSS' => 'useCSS',
                    'useTransform' => 'useTransform',
                    'variableWidth' => 'variableWidth',
                    'vertical' => 'vertical',
                    'verticalSwiping' => 'verticalSwiping',
                    'rtl' => 'rtl',
                    'waitForAnimate' => 'waitForAnimate',
                    'zIndex' => 'zIndex',
                  ),
                  'default_value' => array(
                  ),
                  'allow_null' => 0,
                  'multiple' => 0,
                  'ui' => 1,
                  'ajax' => 0,
                  'return_format' => 'value',
                  'placeholder' => '',
                ),
                array(
                  'key' => 'field_5a26d73ebc6bf',
                  'label' => 'Value',
                  'name' => 'value',
                  'type' => 'textarea',
                  'instructions' => '',
                  'required' => 1,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                  'maxlength' => '',
                  'rows' => '',
                  'new_lines' => '',
                ),
              ),
            ),
          ),
        ),
        array(
          'key' => 'field_5a26cc0e45aaf',
          'label' => 'Additional Settings',
          'name' => 'additional_settings',
          'type' => 'repeater',
          'instructions' => 'Click \'Add Setting\' to add additional settings. For information on the available settings, see <a href="http://kenwheeler.github.io/slick/#settings" target="_blank">http://kenwheeler.github.io/slick/#settings</a>.',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'collapsed' => '',
          'min' => 0,
          'max' => 0,
          'layout' => 'table',
          'button_label' => 'Add Setting',
          'sub_fields' => array(
            array(
              'key' => 'field_5a26cc2445ab0',
              'label' => 'Setting',
              'name' => 'setting',
              'type' => 'select',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
              ),
              'choices' => array(
                'accessibility' => 'accessibility',
                'autoplaySpeed' => 'autoplaySpeed',
                'asNavFor' => 'asNavFor',
                'appendArrows' => 'appendArrows',
                'appendDots' => 'appendDots',
                'centerMode' => 'centerMode',
                'centerPadding' => 'centerPadding',
                'cssEase' => 'cssEase',
                'customPaging' => 'customPaging',
                'dotsClass' => 'dotsClass',
                'draggable' => 'draggable',
                'fade' => 'fade',
                'focusOnSelect' => 'focusOnSelect',
                'easing' => 'easing',
                'edgeFriction' => 'edgeFriction',
                'initialSlide' => 'initialSlide',
                'lazyLoad' => 'lazyLoad',
                'mobileFirst' => 'mobileFirst',
                'pauseOnFocus' => 'pauseOnFocus',
                'pauseOnHover' => 'pauseOnHover',
                'pauseOnDotsHover' => 'pauseOnDotsHover',
                'respondTo' => 'respondTo',
                'rows' => 'rows',
                'slide' => 'slide',
                'slidesPerRow' => 'slidesPerRow',
                'speed' => 'speed',
                'swipe' => 'swipe',
                'swipeToSlide' => 'swipeToSlide',
                'touchMove' => 'touchMove',
                'touchThreshold' => 'touchThreshold',
                'useCSS' => 'useCSS',
                'useTransform' => 'useTransform',
                'variableWidth' => 'variableWidth',
                'vertical' => 'vertical',
                'verticalSwiping' => 'verticalSwiping',
                'rtl' => 'rtl',
                'waitForAnimate' => 'waitForAnimate',
                'zIndex' => 'zIndex',
              ),
              'default_value' => array(
              ),
              'allow_null' => 0,
              'multiple' => 0,
              'ui' => 1,
              'ajax' => 0,
              'return_format' => 'value',
              'placeholder' => '',
            ),
            array(
              'key' => 'field_5a26cc3e45ab1',
              'label' => 'Value',
              'name' => 'value',
              'type' => 'textarea',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => '',
              'maxlength' => '',
              'rows' => '',
              'new_lines' => '',
            ),
          ),
        ),
      ),
    ),
    array(
      'key' => 'field_5a2aa1e4b7b4b',
      'label' => 'Lightbox Options',
      'name' => '',
      'type' => 'tab',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => array(
        array(
          array(
            'field' => 'field_5a2a995f2770d',
            'operator' => '==',
            'value' => '1',
          ),
        ),
      ),
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'placement' => 'top',
      'endpoint' => 0,
    ),
    array(
      'key' => 'field_5a2aa20ab7b4c',
      'label' => 'Lightbox Slideshow Settings',
      'name' => 'slickity_lightbox_settings',
      'type' => 'group',
      'instructions' => 'For more information on the available settings, see <a href="http://kenwheeler.github.io/slick/#settings" target="_blank">http://kenwheeler.github.io/slick/#settings</a>.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'layout' => 'block',
      'sub_fields' => array(
        array(
          'key' => 'field_5a2aa2f1f265d',
          'label' => 'Template',
          'name' => 'template',
          'type' => 'select',
          'instructions' => 'Select the template for the lightbox slide container below, includes styling for the arrows and dots.',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '25',
            'class' => '',
            'id' => '',
          ),
          'choices' => array(
            0 => 'No Template',
            'default' => 'Default Template',
          ),
          'default_value' => array(
            0 => 0,
          ),
          'allow_null' => 0,
          'multiple' => 0,
          'ui' => 1,
          'ajax' => 0,
          'return_format' => 'value',
          'placeholder' => '',
        ),
        array(
          'key' => 'field_5a2aa331f265e',
          'label' => 'CSS Class',
          'name' => 'css',
          'type' => 'text',
          'instructions' => 'You can easily style the lightbox slideshow by adding a CSS class below. Separate multiple classes with a space.',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '25',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'maxlength' => '',
        ),
        array(
          'key' => 'field_5a2aa352f265f',
          'label' => 'Slides to Show',
          'name' => 'slidesToShow',
          'type' => 'number',
          'instructions' => 'Number of slides to show.',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '25',
            'class' => '',
            'id' => '',
          ),
          'default_value' => 1,
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'min' => 1,
          'max' => '',
          'step' => 1,
        ),
        array(
          'key' => 'field_5a2aa376f2660',
          'label' => 'Slides to Scroll',
          'name' => 'slidesToScroll',
          'type' => 'number',
          'instructions' => 'Number of slides to scroll.',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '25',
            'class' => '',
            'id' => '',
          ),
          'default_value' => 1,
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'min' => 1,
          'max' => '',
          'step' => 1,
        ),
        array(
          'key' => 'field_5a2aa394f2661',
          'label' => 'Adaptive Height',
          'name' => 'adaptiveHeight',
          'type' => 'true_false',
          'instructions' => 'Enables adaptive height for single slide horizontal carousels.',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '25',
            'class' => '',
            'id' => '',
          ),
          'message' => '',
          'default_value' => 0,
          'ui' => 1,
          'ui_on_text' => 'True',
          'ui_off_text' => 'False',
        ),
        array(
          'key' => 'field_5a2aa3b3f2662',
          'label' => 'Arrows',
          'name' => 'arrows',
          'type' => 'true_false',
          'instructions' => 'Enable prev/next arrows.',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '25',
            'class' => '',
            'id' => '',
          ),
          'message' => '',
          'default_value' => 1,
          'ui' => 1,
          'ui_on_text' => 'True',
          'ui_off_text' => 'False',
        ),
        array(
          'key' => 'field_5a2aa3cef2663',
          'label' => 'Previous Arrow',
          'name' => 'prevArrow',
          'type' => 'text',
          'instructions' => 'Allows you to select a node or customize the HTML for the "Previous" arrow. Accepts HTML.',
          'required' => 0,
          'conditional_logic' => array(
            array(
              array(
                'field' => 'field_5a2aa3b3f2662',
                'operator' => '==',
                'value' => '1',
              ),
              array(
                'field' => 'field_5a2aa2f1f265d',
                'operator' => '==',
                'value' => '0',
              ),
            ),
          ),
          'wrapper' => array(
            'width' => '25',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '<button type="button" class="slick-prev">Previous</button>',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'maxlength' => '',
        ),
        array(
          'key' => 'field_5a2aa3f0f2665',
          'label' => 'Next Arrow',
          'name' => 'nextArrow',
          'type' => 'text',
          'instructions' => 'Allows you to customize the HTML for the "Next" arrow. Accepts HTML.',
          'required' => 0,
          'conditional_logic' => array(
            array(
              array(
                'field' => 'field_5a2aa3b3f2662',
                'operator' => '==',
                'value' => '1',
              ),
              array(
                'field' => 'field_5a2aa2f1f265d',
                'operator' => '==',
                'value' => '0',
              ),
            ),
          ),
          'wrapper' => array(
            'width' => '25',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '<button type="button" class="slick-next">Next</button>',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'maxlength' => '',
        ),
        array(
          'key' => 'field_5a2aa45cf2667',
          'label' => 'Dots',
          'name' => 'dots',
          'type' => 'true_false',
          'instructions' => 'Enable dot indicators.',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '25',
            'class' => '',
            'id' => '',
          ),
          'message' => '',
          'default_value' => 0,
          'ui' => 1,
          'ui_on_text' => 'True',
          'ui_off_text' => 'False',
        ),
        array(
          'key' => 'field_5a2aa477f2668',
          'label' => 'Responsive Settings',
          'name' => 'responsive',
          'type' => 'true_false',
          'instructions' => 'Define settings for individual breakpoints.',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '25',
            'class' => '',
            'id' => '',
          ),
          'message' => '',
          'default_value' => 0,
          'ui' => 1,
          'ui_on_text' => 'True',
          'ui_off_text' => 'False',
        ),
        array(
          'key' => 'field_5a2aa497f2669',
          'label' => 'Mobile First',
          'name' => 'mobileFirst',
          'type' => 'true_false',
          'instructions' => 'Applies the main settings to mobile first.',
          'required' => 0,
          'conditional_logic' => array(
            array(
              array(
                'field' => 'field_5a2aa477f2668',
                'operator' => '==',
                'value' => '1',
              ),
            ),
          ),
          'wrapper' => array(
            'width' => '25',
            'class' => '',
            'id' => '',
          ),
          'message' => '',
          'default_value' => 0,
          'ui' => 1,
          'ui_on_text' => 'True',
          'ui_off_text' => 'False',
        ),
        array(
          'key' => 'field_5a2aa4bbf266a',
          'label' => 'Responsive Options',
          'name' => 'responsive_options',
          'type' => 'repeater',
          'instructions' => 'Click \'Add Breakpoint\' to define settings for individual breakpoints, then click \'Add Setting\' to add additional settings. For information on the available settings, see <a href="http://kenwheeler.github.io/slick/#settings" target="_blank">http://kenwheeler.github.io/slick/#settings</a>.',
          'required' => 1,
          'conditional_logic' => array(
            array(
              array(
                'field' => 'field_5a2aa477f2668',
                'operator' => '==',
                'value' => '1',
              ),
            ),
          ),
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'collapsed' => '',
          'min' => 0,
          'max' => 0,
          'layout' => 'table',
          'button_label' => '',
          'sub_fields' => array(
            array(
              'key' => 'field_5a2aa4cbf266b',
              'label' => 'Breakpoint',
              'name' => 'breakpoint',
              'type' => 'number',
              'instructions' => '',
              'required' => 1,
              'conditional_logic' => 0,
              'wrapper' => array(
                'width' => '15',
                'class' => '',
                'id' => '',
              ),
              'default_value' => 728,
              'placeholder' => '',
              'prepend' => '',
              'append' => 'px',
              'min' => 1,
              'max' => '',
              'step' => 1,
            ),
            array(
              'key' => 'field_5a2aa4eff266c',
              'label' => 'Settings',
              'name' => 'settings',
              'type' => 'repeater',
              'instructions' => '',
              'required' => 1,
              'conditional_logic' => 0,
              'wrapper' => array(
                'width' => '85',
                'class' => '',
                'id' => '',
              ),
              'collapsed' => '',
              'min' => 0,
              'max' => 0,
              'layout' => 'table',
              'button_label' => 'Add Setting',
              'sub_fields' => array(
                array(
                  'key' => 'field_5a2aa503f266d',
                  'label' => 'Setting',
                  'name' => 'setting',
                  'type' => 'select',
                  'instructions' => '',
                  'required' => 1,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                  ),
                  'choices' => array(
                    'accessibility' => 'accessibility',
                    'adaptiveHeight' => 'adaptiveHeight',
                    'autoplay' => 'autoplay',
                    'autoplaySpeed' => 'autoplaySpeed',
                    'arrows' => 'arrows',
                    'asNavFor' => 'asNavFor',
                    'appendArrows' => 'appendArrows',
                    'appendDots' => 'appendDots',
                    'prevArrow' => 'prevArrow',
                    'nextArrow' => 'nextArrow',
                    'centerMode' => 'centerMode',
                    'centerPadding' => 'centerPadding',
                    'cssEase' => 'cssEase',
                    'customPaging' => 'customPaging',
                    'dots' => 'dots',
                    'dotsClass' => 'dotsClass',
                    'draggable' => 'draggable',
                    'fade' => 'fade',
                    'focusOnSelect' => 'focusOnSelect',
                    'easing' => 'easing',
                    'edgeFriction' => 'edgeFriction',
                    'infinite' => 'infinite',
                    'initialSlide' => 'initialSlide',
                    'lazyLoad' => 'lazyLoad',
                    'mobileFirst' => 'mobileFirst',
                    'pauseOnFocus' => 'pauseOnFocus',
                    'pauseOnHover' => 'pauseOnHover',
                    'pauseOnDotsHover' => 'pauseOnDotsHover',
                    'respondTo' => 'respondTo',
                    'rows' => 'rows',
                    'slide' => 'slide',
                    'slidesPerRow' => 'slidesPerRow',
                    'slidesToShow' => 'slidesToShow',
                    'slidesToScroll' => 'slidesToScroll',
                    'speed' => 'speed',
                    'swipe' => 'swipe',
                    'swipeToSlide' => 'swipeToSlide',
                    'touchMove' => 'touchMove',
                    'touchThreshold' => 'touchThreshold',
                    'useCSS' => 'useCSS',
                    'useTransform' => 'useTransform',
                    'variableWidth' => 'variableWidth',
                    'vertical' => 'vertical',
                    'verticalSwiping' => 'verticalSwiping',
                    'rtl' => 'rtl',
                    'waitForAnimate' => 'waitForAnimate',
                    'zIndex' => 'zIndex',
                  ),
                  'default_value' => array(
                  ),
                  'allow_null' => 0,
                  'multiple' => 0,
                  'ui' => 1,
                  'ajax' => 0,
                  'return_format' => 'value',
                  'placeholder' => '',
                ),
                array(
                  'key' => 'field_5a2aa52df266e',
                  'label' => 'Value',
                  'name' => 'value',
                  'type' => 'textarea',
                  'instructions' => '',
                  'required' => 1,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                  'maxlength' => '',
                  'rows' => '',
                  'new_lines' => '',
                ),
              ),
            ),
          ),
        ),
        array(
          'key' => 'field_5a2aa562f266f',
          'label' => 'Additional Settings',
          'name' => 'additional_settings',
          'type' => 'repeater',
          'instructions' => 'Click \'Add Setting\' to add additional settings. For information on the available settings, see <a href="http://kenwheeler.github.io/slick/#settings" target="_blank">http://kenwheeler.github.io/slick/#settings</a>.',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'collapsed' => '',
          'min' => 0,
          'max' => 0,
          'layout' => 'table',
          'button_label' => 'Add Setting',
          'sub_fields' => array(
            array(
              'key' => 'field_5a2aa578f2670',
              'label' => 'Setting',
              'name' => 'setting',
              'type' => 'select',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
              ),
              'choices' => array(
                'accessibility' => 'accessibility',
                'autoplaySpeed' => 'autoplaySpeed',
                'asNavFor' => 'asNavFor',
                'appendArrows' => 'appendArrows',
                'appendDots' => 'appendDots',
                'centerMode' => 'centerMode',
                'centerPadding' => 'centerPadding',
                'cssEase' => 'cssEase',
                'customPaging' => 'customPaging',
                'dotsClass' => 'dotsClass',
                'draggable' => 'draggable',
                'fade' => 'fade',
                'focusOnSelect' => 'focusOnSelect',
                'easing' => 'easing',
                'edgeFriction' => 'edgeFriction',
                'initialSlide' => 'initialSlide',
                'lazyLoad' => 'lazyLoad',
                'mobileFirst' => 'mobileFirst',
                'pauseOnFocus' => 'pauseOnFocus',
                'pauseOnHover' => 'pauseOnHover',
                'pauseOnDotsHover' => 'pauseOnDotsHover',
                'respondTo' => 'respondTo',
                'rows' => 'rows',
                'slide' => 'slide',
                'slidesPerRow' => 'slidesPerRow',
                'speed' => 'speed',
                'swipe' => 'swipe',
                'swipeToSlide' => 'swipeToSlide',
                'touchMove' => 'touchMove',
                'touchThreshold' => 'touchThreshold',
                'useCSS' => 'useCSS',
                'useTransform' => 'useTransform',
                'variableWidth' => 'variableWidth',
                'vertical' => 'vertical',
                'verticalSwiping' => 'verticalSwiping',
                'rtl' => 'rtl',
                'waitForAnimate' => 'waitForAnimate',
                'zIndex' => 'zIndex',
              ),
              'default_value' => array(
              ),
              'allow_null' => 0,
              'multiple' => 0,
              'ui' => 1,
              'ajax' => 0,
              'return_format' => 'value',
              'placeholder' => '',
            ),
            array(
              'key' => 'field_5a2aa599f2671',
              'label' => 'Value',
              'name' => 'value',
              'type' => 'textarea',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => '',
              'maxlength' => '',
              'rows' => '',
              'new_lines' => '',
            ),
          ),
        ),
      ),
    ),
  ),
  'location' => array(
    array(
      array(
        'param' => 'post_type',
        'operator' => '==',
        'value' => 'slickity_slideshow',
      ),
    ),
  ),
  'menu_order' => 0,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 1,
  'description' => '',
));

endif;
